// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class Course
    {
        public Course()
        {
            CourseLictures = new HashSet<CourseLictures>();
        }

        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public string Title { get; set; }
        public string CoursePhoto { get; set; }
        public string Summery { get; set; }
        public string Requrements { get; set; }
        public int? Duaration { get; set; }
        public int? Price { get; set; }
        public double? Offer { get; set; }
        public string TeacherId { get; set; }
        public bool? IsApproaved { get; set; }
        public string Picture { get; set; }

        public virtual ICollection<CourseLictures> CourseLictures { get; set; }
    }
}