// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class CourseCategory
    {
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CategroryPicture { get; set; }
    }
}