// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class CourseCategoryList
    {
        public int CourseCategoryId { get; set; }
        public int CousrseId { get; set; }

        public virtual CourseCategory CourseCategory { get; set; }
        public virtual Course Cousrse { get; set; }
    }
}