// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models
{
    public partial class CourseCategory
    {
        public CourseCategory()
        {
            Teachers = new HashSet<Teachers>();
        }

        public int CourseCategoryId { get; set; }
        public string CategoryName { get; set; }

        public virtual ICollection<Teachers> Teachers { get; set; }
    }
}