// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models
{
    public partial class Teachers
    {
        public string TeacherId { get; set; }
        public int? DepartmentId { get; set; }
        public string Exceperience { get; set; }
        public string About { get; set; }
        public string Qualification { get; set; }
        public string FacebookLink { get; set; }
        public string TwiterLink { get; set; }
        public string LinkedinLink { get; set; }
        public string InstegramLink { get; set; }

        public virtual CourseCategory Department { get; set; }
    }
}