// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models
{
    public partial class TeacherCourses
    {
        public string TeacherId { get; set; }
        public string CourseName { get; set; }
    }
}