// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models
{
    public partial class TeacherSkills
    {
        public string TeacherId { get; set; }
        public string Skill { get; set; }
        public int? Percentage { get; set; }
    }
}