// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Core.Models
{
    public partial class Teacher
    {
        public string TeacherId { get; set; }
        public string Title { get; set; }
        public string FacebookLink { get; set; }
        public string TwiterLink { get; set; }
        public string GoogleLink { get; set; }
        public string LinkedinLink { get; set; }
        public string Description { get; set; }
        public string About { get; set; }
        public string Acchivments { get; set; }
        public string MyObjective { get; set; }
    }
}